# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2bd183f9c630d630d5cfec591995f96c59d30be825e74d4d26e6c3a787005724b05052eee9c7664147e37d4d58774604c1fe925f6e266c68330ac870fd65db

test:
  secret_key_base: ea107203a60bdb5509d4b3a46f1b6066ff91c0409bd3d6a0c2389c10ae03a42274e9df6e7195d49076099ddcd92b4212a6e40afac898540238eb6b94195d4ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
